sudo: false
language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - hexo-source # store source code of hexo in hexo-source branch
script:
  - hexo clean
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
# added
  target_branch: master # generate static files to master
  on:
    branch: hexo-source # source code of hexo
  local-dir: public

# sudo: false
# language: node_js
# node_js:
#   - 10 # use nodejs v10 LTS
# cache: npm
# branches:
#   only:
#     - master # build master branch only
# script:
#   - hexo generate # generate static files
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GH_TOKEN
#   keep-history: true
#   on:
#     branch: master
#   local-dir: public
